export const actionsTypes = {
  ADD_NEW_EMPLOYEE: "ADD_NEW_EMPLOYEE",
  SELECT_DAY: "SELECT_DAY",
  SELECT_EMPLOYEE: "SELECT_EMPLOYEE",
  SELECT_AVAILABLE_EMPLOYEES: "SELECT_AVAILABLE_EMPLOYEES",
  ADD_HIRED_EMPLOYEE_TO_MORNINGSHIFT: "ADD_HIRED_EMPLOYEE_TO_MORNINGSHIFT",
  ADD_HIRED_EMPLOYEE_TO_EVENINGSHIFT: "ADD_HIRED_EMPLOYEE_TO_EVENINGSHIFT",
  REMOVE_EMPLOYEE_FROM_SHIFT: "REMOVE_EMPLOYEE_FROM_SHIFT",
};
